name: cv_proj1
channels:
  - conda-forge
  - pytorch
dependencies:
  - bandit
  - flake8
  - jupyter
  - matplotlib
  - mypy
  - numpy
  - pytest
  - python>=3.6
  - pyyaml
  - pytorch
  - torchvision
  - Pillow=6.2.1
